pmkpi_optimize_transformation_historical:
   target: databricks_job
   outputs:
     databricks_job:
      type: databricks
      method: http
      schema: "demo_dbt"
      host: "{{ env_var('SQL_HOST') }}"
      http_path: "{{ env_var('SQL_HTTP_PATH') }}"
      token: "{{ env_var('DBT_ACCESS_TOKEN') }}"
